# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
